# Generated by Django 5.2.6 on 2026-05-27 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes del período (ej: 2025-05-01)')),
                ('sueldo_basico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiene_asignacion_familiar', models.BooleanField(default=False)),
                ('tipo_pension', models.CharField(choices=[('ONP', 'ONP — Sistema Nacional de Pensiones (13%)'), ('AFP', 'AFP — Sistema Privado de Pensiones')], default='ONP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Registro de Planilla',
                'verbose_name_plural': 'Registros de Planilla',
                'ordering': ['-periodo', 'empleado__apellido'],
                'unique_together': {('empleado', 'periodo')},
            },
        ),
    ]
